// Goroutine
package main

func main() {
	//goruntine_()
	//channels_()
	//channels_buffering()
	//channel_synchronization()
	//fib()
	//web_route()
	//channel_directions()
	//select_()
	//for_()
	//slices_()
	//maps_()
	//range_()
	//methods_()
	//interfaces_()
	//Timeouts_()
	//channel_non_blocking()
	//channel_close()
	//channel_range()
	//timers_()
	//Tickers_()
	//WorkerPools_()
	//RateLimiting_()
	//AtomicCounters_()
	//Mutexes_()
	//StatefulGoroutines_()
	Defer_()
}
